- name: make sure prerequisites are installed
  apt:
    name: "{{ item }}"
    state: present
    lock_timeout: 180
  become: yes
  with_items:
    - rsync
    - unzip
#     - isc-dhcp-server

# - name: Enable DHCP service
#   service:
#     name: "{{ item }}"
#     state: restarted
#     enabled: yes
#   become: yes
#   with_items:
#     - isc-dhcp-server