
- name: assert all vars are set
  assert: { that: "{{ item }} != '' " }
  with_items:
  - installation_folder
  - temp_folder
  - reboot_after_install

- name: uninstall nvserver
  command: "{{ installation_folder }}/uninstall -q"
  become: yes

- name: remove installation folder
  file:
    path: "{{ installation_folder }}"
    state: absent
  become: yes

- name: remove temp folder
  file:
    path: "{{ temp_folder }}"
    state: absent
  become: yes
  when: clear_temp_folder | default('no') | bool

# reboot the instance after uninstall (optional)

- name: reboot nvserver instance
  reboot:
    reboot_timeout: "{{ reboot_timeout | default(600) }}"
  become: yes
  when: reboot_after_install == True
