---

- name: validate vars
  include_tasks: tasks/variables.yml

- name: install
  include_tasks: "tasks/{{ ansible_os_family | os_family_to_os_type }}-install.yml"
  when: state|default('present') == 'present'

- name: clear temp folder
  include_tasks: "tasks/{{ ansible_os_family | os_family_to_os_type }}-clear-temp.yml"
  when: clear_temp_folder | default('no') | bool
  
- name: uninstall
  include_tasks: "tasks/{{ ansible_os_family | os_family_to_os_type }}-uninstall.yml"
  when: state|default('present') == 'absent'

- name: restart cloud nv
  include_tasks: "tasks/{{ ansible_os_family | os_family_to_os_type }}-restart.yml"
  when: state|default('present') == 'restarted'
