
# restarting nvserver services
- name: start nvserver service
  service:
    name: "{{ item }}"
    state: started
  become: yes
  with_items:
    - nvserver
    - nvproxyserver
    - istpserver
    - dhcpd

- name: stop nvserver service
  service:
    name: "{{ item }}"
    state: stopped
  become: yes
  with_items:
    - nvserver
    - nvproxyserver
    - istpserver
    - dhcpd

  # restarting nvserver services
- name: restart nvserver service
  service:
    name: "{{ item }}"
    state: restarted
  become: yes
  with_items:
    - nvserver
    - nvproxyserver
    - istpserver
    - dhcpd
